<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>tensor_span_test</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NumFlat" Version="1.2.2" />
    <PackageReference Include="System.Numerics.Tensors" Version="11.0.0-preview.1.26104.118" />
  </ItemGroup>

</Project>
